[supabase]
url = "https://cvtpiqvxswcmdhcprqzp.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2dHBpcXZ4c3djbWRoY3BycXpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MzA4NTUsImV4cCI6MjA2MjMwNjg1NX0.p9v5ZSyClhgI0eeUX5233bFsGZkSaUtFAyGYiwiW_2g"

[auth]
password = "blpasset"
